/jail:
    description: "Provides the jail component for the Monopoly game"
    get:
        description: "Returns list of URIs of player resources that are currently in jail"
        queryParameters:
        	filter:
        		displayName: Filter
        		type: string
        		description: "Only return players with a name matching the given pattern"
        		required: false
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {"users": ["/jail/mario"] }
    /{userid}:
        get:
            description: "Returns the state of the player resource"
            responses:
                200:
                    body:
                        application/json:
                            example: |
                                {"id": "/jail/mario",player":"/user/mario","jailed":false}
        put:
            description: "Puts the player into jail"
        delete:
            description: "Removes the player from jail"

